apiVersion: v1
kind: Service
metadata:
  name: service-kiali
  namespace: istio-system
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32183
      targetPort: 20001
  selector:
    app: kiali