apiVersion: v1
kind: ConfigMap
metadata:
  name: userservice-config
data:
  POSTGRES_URI: postgresql://postgres:5432/otus
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  GREETING: Bonjour
---
apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
data:
  POSTGRES_USER: b3R1cw==
  POSTGRES_PASSWORD: b3R1cw==
