{
 "title": "UserService",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(kube_pod_info, cluster)"
   },
   {
    "name": "node",
    "query": "label_values(kube_pod_info{cluster=\"$cluster\"}, node)"
   },
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, instance)" },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*|postgres\"},datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Создание пользователя (Latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Запрос данных пользователя (Latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Запрос всех пользователей (Latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"GET\", uri=\"/users\"}[1m]))))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Service (Error Rate)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, status, uri)(rate(http_server_requests_seconds_count{job=\"userservice-chart\", status=~\"50.\"}[1m]))"
    }
   ]
  },
  {
   "title": "Изменения данных пользователя (Latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"PUT\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Удаление пользователя (Latency)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"DELETE\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"DELETE\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"DELETE\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le, method, uri) (rate(http_server_requests_seconds_bucket{job=\"userservice-chart\", method=\"DELETE\", uri=\"/users/{id}\"}[1m]))))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Service RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri)(rate(http_server_requests_seconds_count{job=\"userservice-chart\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, uri)(rate(nginx_ingress_controller_request_size_count{exported_service=\"userservice-chart\"}[1m]))"
    }
   ]
  },
  {
   "title": "Nginx Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"userservice-chart\"}[1m]))))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"userservice-chart\"}[1m]))))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"userservice-chart\"}[1m]))))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, (sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"userservice-chart\"}[1m]))))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Nginx (Error Rate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method, status)(rate(nginx_ingress_controller_request_size_count{status=~\"50.\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=\"$cluster\", node=\"$node\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", node=\"$node\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "PostgreSQL (Connection)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "pg_stat_activity_count{instance=\"$instance\", datname=\"$db\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "PostreSQL (Transactions)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=\"$db\"}[5m])",
     "legendFormat": "commits"
    },
    {
     "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=\"$db\"}[5m])",
     "legendFormat": "rollbacks"
    }
   ]
  }
 ]
}