apiVersion: batch/v1
kind: Job
metadata:
  name: productservice1
spec:
  template:
    metadata:
      name: productservice1
    spec:
      restartPolicy: Never
      containers:
        - name: post-install-job
          image: postgres:latest
          env:
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: productservice-config1
                  key: POSTGRES_HOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: productservice-config1
                  key: POSTGRES_PORT
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: productservice-secret1
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: productservice-secret1
                  key: POSTGRES_PASSWORD
          command:
            - sh
            - "-c"
            - |
              psql <<'EOF'
              CREATE TABLE products
              (
                guid character(36) NOT NULL,
                name character varying(200),
                color character varying(500),
                category character varying(500),
                price numeric,
                description character varying(1000),
                CONSTRAINT pk_product PRIMARY KEY (guid)
              );
              EOF

  backoffLimit: 10