apiVersion: v1
kind: ConfigMap
metadata:
  name: productservice-config
data:
  POSTGRES_HOST: {{ printf "%s" (include "postgresql.fullname" .) | quote }}
  POSTGRES_PORT: {{ printf "%s" .Values.postgresql.service.port | quote }}
  POSTGRES_URI: {{ printf "postgresql://%s:%s/%s" (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase | quote }}
  GREETING: Bonjour
---
apiVersion: v1
kind: Secret
metadata:
  name: productservice-secret
type: Opaque
data:
  POSTGRES_USER: {{ printf "%s" .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ printf "%s" .Values.postgresql.postgresqlPassword | b64enc | quote }}
