# Default values for deliveryservice.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dskichigin/otus-softwarearchitect
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "deliveryservice"

service:
  type: NodePort
  port: 9000
  targetPort: 8000

ingress:
  enabled: enable
  annotations: { kubernetes.io/ingress.class: nginx, nginx.ingress.kubernetes.io/rewrite-target: /delivery/$2 }
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: arch.homework
      paths: [/otusapp/delivery($|/)(.*)]
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


postgresql:
  enabled: false
  postgresqlUsername: otus
  postgresqlPassword: otus
  postgresqlDatabase: otus
  pgHbaConfiguration: |-
    local all all trust
    host all all 0.0.0.0/0 trust
  service:
    type: NodePort
    port: "5432"

persistence:
  enabled: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
